# Generated by Django 4.1.4 on 2022-12-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="tbrecommend", options={"managed": False},),
    ]
